version: 2
updates:
  - package-ecosystem: "npm" # Specify the package manager for the main project
    directory: "/" # Root directory for the main project's package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # Specify the package manager for the backend
    directory: "/backend" # Directory for the backend's package.json
    schedule:
      interval: "weekly"

